### PR TITLE
Internal overhaul task

### PR DESCRIPTION
**Pull request by DevBefell**
- [x] Move authentication database out of launcher profiles
- [x] Move natives out of HOME/versions/... folder and into HOME/bin
- [x] Fix extra spaces in JVM arguments causing launching issues
- [x] Fix game output throwing stream closed errors with forge
- [x] Fixed indexes not found when cleaning assets
- [x] Proper implementation for Latest Versions.
- [x] Implement Latest Snapshots alongside Latest Versions with proper naming, E.G (Latest Version - 1.20.4)
- [x] Fix/Add?  Custom versions handling - https://github.com/olauncher/olauncher/issues/62

These are somethings I will do within this overhaul.  So far no issues with the new accounts files the other miscellaneous changes.  Would be best to test out before I finish.

### CODE REVIEW

**Comment by DevBefell** [comment]
All is done except for integrity checking as that would require a lot more changes, currently finished the overhaul but need testing to assure it isn't breaking anything.

**Comment by bigfoot547** [comment]
In your fix for #62, do you hide only versions with "custom" release type or all modded versions? (some have release or snapshot build type) Does it affect the "latest version" option?

**Comment by DevBefell** [comment]
Customs are those not in the remote list (version manifest), so those that are not releases, snapshots, old alpha and beta

**Comment by bigfoot547** [comment]
rebased to include new CI stuff

**Comment by bigfoot547** [comment]
RE: latest commit
yeah mojang makes the "latest snapshot" the latest version of any type, be it release or snapshot. "latest release" is just the latest version that is a release

**Review by bigfoot547 — APPROVED** [review]
looks good yay

**Pull request closed without merging**
